run:
  timeout: 5m

  build-tags:
    - upgrade

  skip-dirs:
    - pkg/client

linters:
  enable:
    - asciicheck
    - gofmt
    - goimports
    - golint
    - gosec
    - misspell
    - prealloc
    - stylecheck
    - unconvert
    - unparam
  disable:
    - errcheck

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec
        - unparam
