---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-site-controller
  labels:
    app.kubernetes.io/part-of: skupper
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-site-controller
  template:
    metadata:
      labels:
        application: skupper-site-controller
    spec:
      serviceAccountName: skupper-site-controller
      containers:
        - name: site-controller
          image: quay.io/skupper/site-controller:0.3
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SKUPPER_SERVICE_CONTROLLER_IMAGE
              value: quay.io/skupper/service-controller:0.3