apiVersion: v1
kind: Service
metadata:
  labels:
    name: knative-openshift
  name: knative-openshift-metrics-3
spec:
  ports:
  - name: http-cli
    port: 8080
    protocol: TCP
    targetPort: http-cli
  - name: http-metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    name: knative-openshift
  type: ClusterIP
