apiVersion: v1
kind: Service
metadata:
  labels:
    name: knative-openshift
  name: knative-openshift-metrics
  namespace: placeholder
spec:
  ports:
  - name: http-metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    name: knative-openshift
  type: ClusterIP
